# Generated by Django 6.0.3 on 2026-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(verbose_name='Марка')),
                ('model', models.CharField(verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(verbose_name='Цвет')),
                ('body_type', models.CharField(verbose_name='Тип кузова')),
                ('engine', models.CharField(verbose_name='Двигатель')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Статус продажи')),
                ('fuel', models.CharField(verbose_name='Тип топливо')),
                ('transmission', models.CharField(verbose_name='Трансмиссия')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
        ),
    ]
