# Generated by Django 6.0.3 on 2026-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
    ]
