# Generated by Django 6.0.3 on 2026-04-14 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1900, message="год не может быть меньше чем:1900"
                    ),
                    django.core.validators.MaxValueValidator(
                        2026, message="год не может быть больше чем:2026"
                    ),
                ],
                verbose_name="Год выпуска",
            ),
        ),
    ]
