# Generated by Django 6.0.3 on 2026-04-17 12:12

import django.core.validators
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='Объем двигателя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900, message='год не может быть меньше чем:1900'),
                    django.core.validators.MaxValueValidator(2026, message='год не может быть больше чем:2026'),
                ],
                verbose_name='Год выпуска',
            ),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='api.brand',
                verbose_name='Марка',
            ),
        ),
    ]
