# Generated by Django 6.0.3 on 2026-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_brand_remove_car_engine_car_engine_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Пробег'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена (Euro)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
