# Generated by Django 6.0.3 on 2026-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_car_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='on_main_page',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
    ]
