# Generated by Django 6.0.3 on 2026-04-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_car_description_car_mileage_alter_car_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={
                'ordering': ('price',),
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='cars/main/',
                verbose_name='Главное фото',
            ),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(upload_to='cars/gallery/', verbose_name='Фото'),
                ),
                (
                    'car',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='api.car',
                        verbose_name='Автомобиль',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
