# Generated by Django 6.0.3 on 2026-04-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_servis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servis',
            new_name='Service',
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
