# Generated by Django 6.0.3 on 2026-04-07 15:31

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_category_servis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "Автомобиль", "verbose_name_plural": "Автомобили"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AddField(
            model_name="car",
            name="eco_sticker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zero", "0 (Cero emisiones)"),
                    ("eco", "ECO"),
                    ("c", "C"),
                    ("b", "B"),
                ],
                max_length=20,
                null=True,
                verbose_name="Эконаклейка",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Седан"),
                    ("suv", "Внедорожник"),
                    ("hatchback", "Хэтчбек"),
                    ("wagon", "Универсал"),
                    ("coupe", "Купе"),
                    ("convertible", "Кабриолет"),
                    ("minivan", "Минивэн"),
                    ("pickup", "Пикап"),
                    ("crossover", "Кроссовер"),
                ],
                max_length=20,
                verbose_name="Тип кузова",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(max_length=100, verbose_name="Марка"),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Белый"),
                    ("black", "Чёрный"),
                    ("silver", "Серебристый"),
                    ("gray", "Серый"),
                    ("red", "Красный"),
                    ("blue", "Синий"),
                    ("green", "Зелёный"),
                    ("brown", "Коричневый"),
                    ("beige", "Бежевый"),
                    ("yellow", "Жёлтый"),
                    ("orange", "Оранжевый"),
                    ("other", "Другой"),
                ],
                default="other",
                max_length=20,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(max_length=100, verbose_name="Двигатель"),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel",
            field=models.CharField(
                choices=[
                    ("petrol", "Бензин"),
                    ("diesel", "Дизель"),
                    ("hybrid", "Гибрид"),
                    ("electric", "Электро"),
                    ("gas", "Газ (LPG)"),
                ],
                max_length=20,
                verbose_name="Тип топлива",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Цена должна быть положительной"
                    )
                ],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[
                    ("manual", "Механика"),
                    ("automatic", "Автомат"),
                    ("cvt", "Вариатор"),
                    ("robot", "Робот"),
                ],
                max_length=20,
                verbose_name="Трансмиссия",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(
                validators=[api.models.validate_year], verbose_name="Год выпуска"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "price",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Цена должна быть положительной"
                            )
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.DeleteModel(
            name="Servis",
        ),
    ]
