# Generated by Django 6.0.3 on 2026-05-31 10:45

import api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_car_options_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_es',
            field=models.TextField(blank=True, default='', verbose_name='Описание (ES)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (ES)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (ES)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/main/', validators=[api.validators.validate_file_extension, api.validators.validate_file_size], verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/gallery/', validators=[api.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название (RU)'),
        ),
    ]
