# Generated by Django 6.0.3 on 2026-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_car_description_en_car_description_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
