# Generated by Django 6.0.3 on 2026-04-10 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_car_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Цена должна быть положительной')], verbose_name='Цена (Euro)'),
        ),
    ]
