# Generated by Django 6.0.3 on 2026-08-11 14:09

import django.core.validators
from django.db import migrations, models


def cc_to_liters(apps, schema_editor):
    Car = apps.get_model('api', 'Car')
    for car in Car.objects.all():
        car.engine_capacity = round(car.engine_capacity / 1000, 1)
        car.save(update_fields=['engine_capacity'])


def liters_to_cc(apps, schema_editor):
    Car = apps.get_model('api', 'Car')
    for car in Car.objects.all():
        car.engine_capacity = round(car.engine_capacity * 1000)
        car.save(update_fields=['engine_capacity'])


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_alter_service_price'),
    ]

    operations = [
        # Промежуточный широкий тип: старые значения хранятся в см³ (2500 и т.п.)
        # и не влезают в финальный numeric(3, 1), пока не поделены на 1000.
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.RunPython(cc_to_liters, liters_to_cc),
    ]
