# Generated by Django 6.0.3 on 2026-08-11 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_alter_car_engine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Объем двигателя (л)',
            ),
        ),
    ]
