from datetime import datetime


CAR_YEAR_MAX = datetime.now().year
CAR_YEAR_MIN = 1900
CAR_NAME_MAX_LENGTH = 100
CAR_CHOICE_MAX_LENGTH = 20
SERVICE_PRICE_MIN = 1
SERVICE_NAME_MAX_LENGTH = 200
CACHE_EXPIRATION = 60

ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png', 'webp'}
MAX_FILE_SIZE = 6 * 1024 * 1024
