from datetime import datetime

CAR_YEAR_MAX = datetime.now().year
CAR_YEAR_MIN = 1900
CAR_NAME_MAX_LENGTH = 100
CAR_CHOICE_MAX_LENGTH = 20
CAR_PRICE_MIN = 1
SERVICE_PRICE_MIN = 1
SERVICE_NAME_MAX_LENGTH = 200
