from datetime import datetime

PAGE_SIZE = 6
MAX_PAGE_SIZE = 48

CAR_YEAR_MAX = datetime.now().year
CAR_YEAR_MIN = 1900
CAR_NAME_MAX_LENGTH = 100
CAR_CHOICE_MAX_LENGTH = 20
SERVICE_PRICE_MIN = 1
SERVICE_NAME_MAX_LENGTH = 200
CACHE_EXPIRATION = 60
