volumes:
  media:
  static:
  redis_data:
  pg_data:

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    env_file: ./.env
    networks:
      - app-network

  db:
    image: "postgres:17-alpine"
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ./.env
    networks:
      - app-network

  backend:
    build: ./backend/
    container_name: backend
    env_file: ./.env
    depends_on:
      - redis
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge