[project]
name = "AutosCar"
version = "1.0.0"
description = "веб-сайта автосалона AutosCar"
requires-python = ">=3.12"
dynamic = ["dependencies", "classifiers"]
authors = ["MeTi", "ViKi"]
readme = "README.md"


[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "Q", "D"]
ignore = [
    "A005",   # allow to shadow stdlib and builtin module names
    "COM812", # trailing comma, conflicts with `ruff format`
    # Different doc rules that we don't really care about:
    "D100",
    "D101",
    "D102",
    "D104",
    "D106",
    "D203",
    "D212",
    "D401",
    "D404",
    "D405",
    "ISC001",  # implicit string concat conflicts with `ruff format`
    "ISC003",  # prefer explicit string concat over implicit concat
    "PLR09",   # we have our own complexity rules
    "PLR2004", # do not report magic numbers
    "PLR6301", # do not require classmethod / staticmethod when self not used
    "TRY003",  # long exception messages from `tryceratops`
]

# Plugin configs:
flake8-quotes.inline-quotes = "single"


[tool.ruff.lint.per-file-ignores]
"*/migrations/*.py" = ["D101", "E501", "RUF012", "Q000"]
"*/tests/*.py" = ["S101", "D100", "D101", "D102", "D103", "D107"]
"*/models.py" = ["D105"]

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true
skip-magic-trailing-comma = false
exclude = []
[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "autoscar.settings"
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "--no-migrations"

[tool.coverage.run]
source = ["."]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/__pycache__/*",
    "autoscar/settings.py",
    "autoscar/wsgi.py",
    "autoscar/asgi.py",
    "manage.py",
    "test_database.py",
    "venv/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]
[tool.ruff.lint.isort]
known-first-party = ["api"]
lines-after-imports = 2
lines-between-types = 1
