server {
    listen 80;
    server_name autoscar.es www.autoscar.es;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name autoscar.es www.autoscar.es;
    index index.html;
    client_max_body_size 50M;

    ssl_certificate /etc/letsencrypt/live/autoscar.es/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/autoscar.es/privkey.pem;

    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
    }

    location /adminka/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/adminka/;
    }

    location /static/ {
        alias /staticfiles/;
    }

    location / {
        alias /staticfiles/;
        try_files $uri $uri/ /index.html;
    }

    location /media/ {
        alias /media/;
    }
}
